### ISSUE TITLE
idea for improvement, TACS, stats, view previous

### ISSUE THREAD

**Issue by tirespider** [rgv151/CNCTAScriptCollection#34]
What I would find most useful is seeing both the current and one previous stats on the same line so I can compare my this sim with the last one.  All I do now is try to memorize the vital stats for a few seconds when it disappears to get refreshed.  My head must be full of thousands of TACS stats that I could have mentally firewalled just by looking at the last two sims together.  Only need the right column.  One easy way would be to not close the last stat window and have the new one overlap it so the last column shows underneath,  Then the next one overlaps that and the first one goes away.  Or you could add a new column and make the second from the right the previous stats.

**Comment by PaymanSh** [comment]
hey would it be possible to change the code back to what it was before this last upgrade?
it doesnt have the **base scanner** and **main menu**

**Comment by rgv151** [comment]
I added them back in latest release

**Comment by PaymanSh** [comment]
i just tested it and its not working!

**Comment by PaymanSh** [comment]
nevermind -- its working haha .. thanks

**Comment by rgv151** [comment]
congrast :+1:

**Comment by fibric** [comment]
another great script https://greasyfork.org/en/scripts/10382-c-c-tiberium-alliances-xtr1m-s-base-overlay

**Comment by rgv151** [comment]
i will add it soon, thanks

**Comment by rgv151** [comment]
added
