### ISSUE TITLE
xTrim's script not running

### ISSUE THREAD

**Issue by fibric** [rgv151/CNCTAScriptCollection#36]
Hi,

regarding to #34 where xTrim was mentioned by me and added.
Running Chrome on OSX and script is not fully executed.

For testing, I have disabled all plugins.

![screen shot 2015-07-01 at 20 47 45](https://cloud.githubusercontent.com/assets/623932/8462203/74454748-2032-11e5-90b9-78a9d6a11847.png)

But I'm not finding the expected console message
https://greasyfork.org/en/scripts/10382-c-c-tiberium-alliances-xtr1m-s-base-overlay/code#n61
nor do I see the error message
https://greasyfork.org/en/scripts/10382-c-c-tiberium-alliances-xtr1m-s-base-overlay/code#n58

![screen shot 2015-07-01 at 20 47 14](https://cloud.githubusercontent.com/assets/623932/8462194/641f4d78-2032-11e5-93bb-333731619395.png)

When I copy and paste the entire script into console. Then I see `xTr1m's Base Overlay script: Initialising finshed`
![screen shot 2015-07-01 at 20 50 14](https://cloud.githubusercontent.com/assets/623932/8462244/cafd0b7a-2032-11e5-87bf-db7433ab47b7.png)

And press and hold ctrl key shows the expected overlay window.
![screen shot 2015-07-01 at 20 53 14](https://cloud.githubusercontent.com/assets/623932/8462331/59194f36-2033-11e5-8283-26470b3aad3b.png)

**Comment by fibric** [comment]
Trying a little more now getting `qx.ui.table.columnmodel.Resize is not a function`
![screen shot 2015-07-01 at 21 05 08](https://cloud.githubusercontent.com/assets/623932/8462559/043fb854-2035-11e5-9c55-64e117954761.png)

Maybe thats the reason. But that does not happen when copy and pasting the original script directly into console.

**Comment by rgv151** [comment]
sorry my bad, script file name is wrong. going to fix it now

**Comment by rgv151** [comment]
updated, thanks

**Comment by fibric** [comment]
:+1:
